// forest_search.cpp -- exact search for Leech trees of order n WITHOUT fixing the topology (Calhoun et al. 2007, Alg 2.7,
// with modern data structures and complete isomorph rejection).
//
// Search tree: nodes are weighted forests F that are candidate sub-forests of a Leech tree.  By the forcing lemma
// (Calhoun Lemma 2.6 / SWZ) the next edge weight is t = least target value not yet a distance in F, and the edge is
// added in one of three ways: (1) joining two components at vertices (x,y); (2) attaching a new vertex to x; (3) a new
// disjoint edge.  Prunes: all new distances distinct, unrealised, and inside the target set; w_i + w_j <= N for the two
// largest weights (any two edges lie on a common path); vertex/component budget (each remaining edge removes at most one
// unit of (components-1) + (n-|V|)).  Every abstract weighted forest is generated exactly once: the parent of a forest is
// unique (remove the max-weight edge) and Aut(F) of a forest with distinct weights is generated by the endpoint swaps of
// its single-edge components, so only the smaller-index endpoint of a single-edge component is used as an attachment.
// The whole tree is shared by all topologies (the per-topology engine leech_search.cpp redoes it 10^5 times at n=18).
// Output: unlabeled Leech trees ("SOL:" lines, one per weighted tree up to isomorphism), node counts per depth.
// Usage: forest_search n [--target v1,v2,...] [--shard i K [--shard-level L]] [-q] [--nodes L]
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <chrono>
#include <algorithm>
using namespace std; typedef uint64_t u64; typedef uint32_t u32;
#ifndef NW
#define NW 3
#endif
struct BS { u64 w[NW];
  void clear() { for (int i = 0; i < NW; i++) w[i] = 0; }
  void set(int i) { w[i >> 6] |= 1ULL << (i & 63); }
  bool test(int i) const { return w[i >> 6] >> (i & 63) & 1; }
  void reset(int i) { w[i >> 6] &= ~(1ULL << (i & 63)); }
  BS shl(int s) const { BS r; r.clear(); int q = s >> 6, b = s & 63; for (int i = NW - 1; i - q >= 0; i--) { int j = i - q; u64 v = w[j] << b; if (b && j - 1 >= 0) v |= w[j - 1] >> (64 - b); r.w[i] = v; } return r; }
  void orw(const BS& o) { for (int i = 0; i < NW; i++) w[i] |= o.w[i]; }
  int count() const { int c = 0; for (int i = 0; i < NW; i++) c += __builtin_popcountll(w[i]); return c; }
  bool inter(const BS& o) const { for (int i = 0; i < NW; i++) if (w[i] & o.w[i]) return true; return false; }
  int lowestMissingIn(const BS& F, int v, int N) const { for (; v <= N; v++) if (F.test(v) && !test(v)) return v; return N + 1; }
};
static const int MAXV = 20;
static int n, N, E; static long long nodes = 0, nsol = 0, depthHist[40], nodeLimit = -1; static bool printSol = true, aborted = false;
static int shardI = 0, shardK = 1, shardLevel = 8; static long long shardCnt = 0;
static int dist_[MAXV][MAXV], comp[MAXV], V; static u32 cm[MAXV]; static BS D0[MAXV]; static int hiD[MAXV];   // D0[x] = {0} U {d(x,x') : x' in comp(x)}
static BS R, FULL; static int eu[MAXV], ev[MAXV], ew[MAXV], ne = 0;
static BS saveD[MAXV][MAXV]; static int saveHi[MAXV][MAXV]; static u32 saveCm[MAXV][2]; static int saveV[MAXV];
static void rec();
// add edge (x,y) with weight t; y is a new vertex if ynew.  New distances = union over x' in C_x of (D0[y] << (d(x',x)+t)).
static void tryAdd(int x, int y, int t, bool ynew) {
  u32 mx = cm[comp[x]], my = ynew ? (1u << y) : cm[comp[y]];
  int ncx = __builtin_popcount(mx), ncy = __builtin_popcount(my);
  BS Dy; int hy; if (ynew) { Dy.clear(); Dy.set(0); hy = 0; } else { Dy = D0[y]; hy = hiD[y]; }
  BS U; U.clear();
  if (ncx <= ncy) { for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); int sh = dist_[xi][x] + t; if (sh + hy > N) return; U.orw(Dy.shl(sh)); } }
  else { const BS& Dx = D0[x]; int hx = hiD[x]; for (u32 m = my; m; m &= m - 1) { int yj = __builtin_ctz(m); int sh = (ynew ? 0 : dist_[yj][y]) + t; if (sh + hx > N) return; U.orw(Dx.shl(sh)); } }
  if (U.count() != ncx * ncy) return;                       // a new distance obtained twice
  if (U.inter(R)) return;                                   // a new distance already realised
  for (int i = 0; i < NW; i++) if (U.w[i] & ~FULL.w[i]) return;   // outside the target set
  int lv = ne; saveV[lv] = V; int cxid = comp[x], cyid = ynew ? y : comp[y];
  saveCm[lv][0] = cm[cxid]; if (!ynew) saveCm[lv][1] = cm[cyid];
  for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); saveD[lv][xi] = D0[xi]; saveHi[lv][xi] = hiD[xi]; }
  for (u32 m = my; m; m &= m - 1) { int yj = __builtin_ctz(m); saveD[lv][yj] = D0[yj]; saveHi[lv][yj] = hiD[yj]; }
  if (ynew) { V++; comp[y] = y; cm[y] = 1u << y; D0[y].clear(); D0[y].set(0); hiD[y] = 0; }
  for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); for (u32 m2 = my; m2; m2 &= m2 - 1) { int yj = __builtin_ctz(m2); int d = dist_[xi][x] + t + (ynew ? 0 : dist_[yj][y]); dist_[xi][yj] = dist_[yj][xi] = d; } }
  { BS Dx = D0[x]; int hx = hiD[x];
    for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); int sh = dist_[xi][x] + t; D0[xi].orw(Dy.shl(sh)); hiD[xi] = max(hiD[xi], sh + hy); }
    for (u32 m = my; m; m &= m - 1) { int yj = __builtin_ctz(m); int sh = (ynew ? 0 : dist_[yj][y]) + t; D0[yj].orw(Dx.shl(sh)); hiD[yj] = max(hiD[yj], sh + hx); } }
  for (u32 m = my; m; m &= m - 1) comp[__builtin_ctz(m)] = cxid;
  cm[cxid] = mx | my;
  R.orw(U); eu[ne] = x; ev[ne] = y; ew[ne] = t; ne++;
  rec();
  ne--; for (int i = 0; i < NW; i++) R.w[i] &= ~U.w[i];
  for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); D0[xi] = saveD[lv][xi]; hiD[xi] = saveHi[lv][xi]; }
  for (u32 m = my; m; m &= m - 1) { int yj = __builtin_ctz(m); D0[yj] = saveD[lv][yj]; hiD[yj] = saveHi[lv][yj]; comp[yj] = cyid; }
  cm[cxid] = saveCm[lv][0]; if (!ynew) cm[cyid] = saveCm[lv][1];
  V = saveV[lv];
}
static void rec() {
  if (aborted) return;
  nodes++; depthHist[ne]++;
  if (nodeLimit > 0 && nodes >= nodeLimit) { aborted = true; return; }
  if (ne == shardLevel && shardK > 1) { if ((shardCnt++) % shardK != shardI) return; }
  int t = R.lowestMissingIn(FULL, 1, N);
  if (t > N) { if (ne == E && V == n) { nsol++; if (printSol) { printf("SOL:"); for (int i = 0; i < ne; i++) printf(" %d-%d:%d", eu[i], ev[i], ew[i]); printf("\n"); fflush(stdout); } } return; }
  if (ne >= E) return;
  if (ne > 0 && t + ew[ne - 1] > N) return;                     // any two edges lie on a common path: w_i + w_j <= N
  int ncomp = V - ne; if (E - ne < ncomp - 1 + (n - V)) return;   // each remaining edge fixes at most one unit of deficit
  u32 elig = 0; for (int i = 0; i < V; i++) { u32 c = cm[comp[i]]; if (__builtin_popcount(c) == 2 && (int)__builtin_ctz(c) != i) continue; elig |= 1u << i; }
  for (u32 m = elig; m; m &= m - 1) { int x = __builtin_ctz(m); u32 rest = elig & ~cm[comp[x]] & ~((2u << x) - 1); for (u32 m2 = rest; m2; m2 &= m2 - 1) tryAdd(x, __builtin_ctz(m2), t, false); }
  if (V < n) for (u32 m = elig; m; m &= m - 1) tryAdd(__builtin_ctz(m), V, t, true);
  if (V + 2 <= n && FULL.test(t)) { int x = V, y = V + 1; int lv = ne; saveV[lv] = V; V += 2; comp[x] = x; comp[y] = x; cm[x] = (1u << x) | (1u << y); dist_[x][y] = dist_[y][x] = t;
    D0[x].clear(); D0[x].set(0); D0[x].set(t); D0[y] = D0[x]; hiD[x] = hiD[y] = t; R.set(t); eu[ne] = x; ev[ne] = y; ew[ne] = t; ne++; rec(); ne--; R.reset(t); V = saveV[lv]; }
}
int main(int argc, char** argv) {
  if (argc < 2) { fprintf(stderr, "usage: forest_search n [--target v1,v2,...] [--shard i K] [--shard-level L] [--nodes L] [-q]\n"); return 1; }
  n = atoi(argv[1]); N = n * (n - 1) / 2; E = n - 1; V = 0; R.clear(); FULL.clear(); bool haveT = false;
  for (int i = 2; i < argc; i++) {
    if (!strcmp(argv[i], "--target")) { haveT = true; N = 0; const char* q = argv[++i]; while (*q) { int v = atoi(q); FULL.set(v); if (v > N) N = v; while (*q && *q != ',') q++; if (*q) q++; } }
    else if (!strcmp(argv[i], "--shard")) { shardI = atoi(argv[++i]); shardK = atoi(argv[++i]); }
    else if (!strcmp(argv[i], "--shard-level")) shardLevel = atoi(argv[++i]);
    else if (!strcmp(argv[i], "--nodes")) nodeLimit = atoll(argv[++i]);
    else if (!strcmp(argv[i], "-q")) printSol = false;
  }
  if (!haveT) for (int v = 1; v <= N; v++) FULL.set(v);
  if (n > MAXV - 1 || N > 64 * NW - 2) { fprintf(stderr, "n too large for this build\n"); return 1; }
  auto t0 = chrono::steady_clock::now();
  rec();
  double dt = chrono::duration<double>(chrono::steady_clock::now() - t0).count();
  printf("{\"n\": %d, \"status\": \"%s\", \"nsol\": %lld, \"nodes\": %lld, \"time\": %.3f, \"shard\": [%d, %d, %d]}\n", n, aborted ? "UNKNOWN" : "DONE", nsol, nodes, dt, shardI, shardK, shardLevel);
  fprintf(stderr, "n=%d nodes=%lld nsol=%lld time=%.2f\ndepth:", n, nodes, nsol, dt); for (int d = 0; d <= E; d++) fprintf(stderr, " %d:%lld", d, depthHist[d]); fprintf(stderr, "\n");
  return 0;
}
