// forest_search_d4.cpp -- DIAMETER<=4 restricted exact search for Leech trees of order n (scratch copy of the
// refereed repo engine src/forest_search.cpp with the additions marked D4:).
// D4 invariant (proved in the session report): every component of a subforest of a hop-diameter<=4 tree has hop
// diameter <= 4 and at most one component has hop diameter >= 3; conversely any such forest is completable.
// Also adds the universal containment cap t <= N-n+2 (every edge has c_e >= n-1, Lemma 4c of docs/theory-notes.md).
// Base: exact search for Leech trees of order n WITHOUT fixing the topology (Calhoun et al. 2007, Alg 2.7,
// with modern data structures and complete isomorph rejection).
//
// Search tree: nodes are weighted forests F that are candidate sub-forests of a Leech tree.  By the forcing lemma
// (Calhoun Lemma 2.6 / SWZ) the next edge weight is t = least target value not yet a distance in F, and the edge is
// added in one of three ways: (1) joining two components at vertices (x,y); (2) attaching a new vertex to x; (3) a new
// disjoint edge.  Prunes: all new distances distinct, unrealised, and inside the target set; w_i + w_j <= N for the two
// largest weights (any two edges lie on a common path); vertex/component budget (each remaining edge removes at most one
// unit of (components-1) + (n-|V|)).  Every abstract weighted forest is generated exactly once: the parent of a forest is
// unique (remove the max-weight edge) and Aut(F) of a forest with distinct weights is generated by the endpoint swaps of
// its single-edge components, so only the smaller-index endpoint of a single-edge component is used as an attachment.
// The whole tree is shared by all topologies (the per-topology engine leech_search.cpp redoes it 10^5 times at n=18).
// Output: unlabeled Leech trees ("SOL:" lines, one per weighted tree up to isomorphism), node counts per depth.
// Usage: forest_search n [--target v1,v2,...] [--shard i K [--shard-level L]] [-q] [--nodes L]
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <chrono>
#include <algorithm>
using namespace std; typedef uint64_t u64; typedef uint32_t u32;
#ifndef NW
#define NW 6
#endif
struct BS { u64 w[NW];
  void clear() { for (int i = 0; i < NW; i++) w[i] = 0; }
  void set(int i) { w[i >> 6] |= 1ULL << (i & 63); }
  bool test(int i) const { return w[i >> 6] >> (i & 63) & 1; }
  void reset(int i) { w[i >> 6] &= ~(1ULL << (i & 63)); }
  BS shl(int s) const { BS r; r.clear(); int q = s >> 6, b = s & 63; for (int i = NW - 1; i - q >= 0; i--) { int j = i - q; u64 v = w[j] << b; if (b && j - 1 >= 0) v |= w[j - 1] >> (64 - b); r.w[i] = v; } return r; }
  void orw(const BS& o) { for (int i = 0; i < NW; i++) w[i] |= o.w[i]; }
  int count() const { int c = 0; for (int i = 0; i < NW; i++) c += __builtin_popcountll(w[i]); return c; }
  bool inter(const BS& o) const { for (int i = 0; i < NW; i++) if (w[i] & o.w[i]) return true; return false; }
  int lowestMissingIn(const BS& F, int v, int N) const { for (; v <= N; v++) if (F.test(v) && !test(v)) return v; return N + 1; }
};
static const int MAXV = 28;
static int n, N, E; static long long nodes = 0, nsol = 0, depthHist[40], nodeLimit = -1; static long long ncompHist[40][8]; static bool printSol = true, aborted = false;
static int shardI = 0, shardK = 1, shardLevel = 8; static long long shardCnt = 0;
static int dist_[MAXV][MAXV], comp[MAXV], V; static u32 cm[MAXV]; static BS D0[MAXV]; static int hiD[MAXV];
static int hop_[MAXV][MAXV], hiH[MAXV]; static int bigCnt = 0;   // D4: hop dists / hop ecc within comp / #comps with hop-diam>=3   // D0[x] = {0} U {d(x,x') : x' in comp(x)}
static BS R, FULL; static int eu[MAXV], ev[MAXV], ew[MAXV], ne = 0;
static BS saveD[MAXV][MAXV]; static int saveHi[MAXV][MAXV]; static u32 saveCm[MAXV][2]; static int saveV[MAXV];
static int saveHiH[MAXV][MAXV]; static int saveBig[MAXV];   // D4
static void rec();
// D4 assembly CSP: with the big component's centre fixed at c0, the remaining ncomp-1 joins are edges
// (c0, s_i) with distinct target weights xi_i in feas_i (each dry-run-compatible with today's state), and the
// pairwise values xi_i + xi_j are the future centre-centre distances d(s_i, s_j): they must be distinct target
// values, unrealised today, distinct from each other and from the xi's.  When every remaining edge is a join
// (E-ne == ncomp-1) the smallest xi must equal t (the very next forced weight).  All of this is a monotone
// relaxation of the true completion, so exhaustive failure is a sound kill; the DFS is budget-capped and
// reports "alive" when the budget runs out.
static int cspBudget;
static int cspChosen[MAXV];
static bool cspGo(BS* dom, int k, int nsets, const BS& RnotF, BS& vals, int minxi_forced) {
  if (k == nsets) return true;
  if (--cspBudget < 0) return true;   // give up = alive
  for (int xi = 1; xi <= N; xi++) {
    if (!dom[k].test(xi)) continue;
    if (vals.test(xi)) continue;
    if (k == 0 && minxi_forced && xi != minxi_forced) continue;
    bool ok = true;
    for (int j = 0; j < k; j++) { int sxx = xi + cspChosen[j];
      if (sxx > N || RnotF.test(sxx) || vals.test(sxx)) { ok = false; break; } }
    if (!ok) continue;
    // commit
    int added[MAXV], na = 0;
    vals.set(xi); added[na++] = xi;
    for (int j = 0; j < k; j++) { int sxx = xi + cspChosen[j]; vals.set(sxx); added[na++] = sxx; }
    cspChosen[k] = xi;
    if (cspGo(dom, k + 1, nsets, RnotF, vals, minxi_forced)) { for (int a = 0; a < na; a++) vals.reset(added[a]); return true; }
    for (int a = 0; a < na; a++) vals.reset(added[a]);
  }
  return false;
}
// feasibility set of star s against a FIXED centre c0
static void feasForCand(u32 mbig, int c0, int s, const BS& feas, const BS& RnotF, BS& out) {
  out.clear();
  for (int xi = 1; xi <= N; xi++) {
    if (!feas.test(xi)) continue;
    u32 ms = cm[comp[s]];
    bool ok = true; BS U; U.clear();
    if (__builtin_popcount(ms) <= __builtin_popcount(mbig)) {
      for (u32 m2 = ms; m2; m2 &= m2 - 1) { int b = __builtin_ctz(m2); int sh = (b == s ? 0 : dist_[b][s]) + xi;
        if (sh + hiD[c0] > N) { ok = false; break; }
        BS T = D0[c0].shl(sh); if (T.inter(RnotF) || T.inter(U)) { ok = false; break; } U.orw(T); }
    } else {
      for (u32 m2 = mbig; m2; m2 &= m2 - 1) { int a = __builtin_ctz(m2); int sh = (a == c0 ? 0 : dist_[a][c0]) + xi;
        if (sh + hiD[s] > N) { ok = false; break; }
        BS T = D0[s].shl(sh); if (T.inter(RnotF) || T.inter(U)) { ok = false; break; } U.orw(T); }
    }
    if (ok) out.set(xi);
  }
}

// D4: dry-run attachability.  Once a big (hop-diam>=3) component exists, the final centre c is one of its
// vertices with hop-ecc <= 2, and every other component must later join by an edge (c, attach) at some weight
// xi >= t; xi is a target value unrealised today; the join edge finally has one side with >= sig = |S| vertices
// and the other with >= n - ... so c_e >= sig(n-sig) (s(n-s) minimised at the interval ends), giving
// xi <= N + 1 - sig(n-sig).  The join creates the distances {d(a,c) + xi + d(attach,b)}; testing them against
// TODAY's realised set / distance sets is a monotone relaxation (all sets only grow), so failure for every xi
// and every centre candidate is a sound kill.  weakFeas alone (star-side translate only) is a necessary
// condition for attaching to ANY centre, even one on a component that does not exist yet.
static void weakFeas(int s, int tmin, const BS& RnotF, BS& feas) {
  int sig = __builtin_popcount(cm[comp[s]]);
  // the future edge (c, s) has branch side in [sig, n - M] where M = vertices currently in OTHER
  // components (they all end up on the c-side); s(n-s) is minimised at the interval ends.
  int M = V - sig; if (M < 1) M = 1;
  long long ce1 = (long long)sig * (n - sig), ce2 = (long long)M * (n - M);
  long long ce = ce1 < ce2 ? ce1 : ce2;
  int cap = (int)(N + 1 - ce); if (cap > N - n + 2) cap = N - n + 2;
  feas.clear(); if (cap < tmin) return;
  for (int v = tmin; v <= cap; v++) feas.set(v);
  u32 ms = cm[comp[s]];
  for (int i = 0; i < NW; i++) feas.w[i] &= ~RnotF.w[i];   // a = 0 term
  for (u32 m2 = ms; m2; m2 &= m2 - 1) { int b = __builtin_ctz(m2); if (b == s) continue; int a = dist_[b][s];
    int q = a >> 6, r = a & 63;
    for (int i = 0; i + q < NW; i++) { u64 v = RnotF.w[i + q] >> r; if (r && i + q + 1 < NW) v |= RnotF.w[i + q + 1] << (64 - r); feas.w[i] &= ~v; }
  }
}
static void tryAdd(int x, int y, int t, bool ynew) {
  u32 mx = cm[comp[x]], my = ynew ? (1u << y) : cm[comp[y]];
  int ncx = __builtin_popcount(mx), ncy = __builtin_popcount(my);
  // D4: hop-diameter invariant ------------------------------------------------
  int eccxH = hiH[x], eccyH = ynew ? 0 : hiH[y];
  int dCx = 0; for (u32 m = mx; m; m &= m - 1) { int i = __builtin_ctz(m); if (hiH[i] > dCx) dCx = hiH[i]; }
  int dCy = 0; if (!ynew) for (u32 m = my; m; m &= m - 1) { int i = __builtin_ctz(m); if (hiH[i] > dCy) dCy = hiH[i]; }
  int ndiam = eccxH + 1 + eccyH; if (dCx > ndiam) ndiam = dCx; if (dCy > ndiam) ndiam = dCy;
  if (ndiam > 4) return;
  if (!ynew) {  // universal: this edge finally has c_e >= min(ncx(n-ncx), ncy(n-ncy))
    long long cel = (long long)ncx * (n - ncx), cer = (long long)ncy * (n - ncy); if (cer < cel) cel = cer;
    if (t > N + 1 - cel) return; }
  int wasBig = (dCx >= 3 ? 1 : 0) + (dCy >= 3 ? 1 : 0);
  if (ndiam >= 3 && bigCnt - wasBig >= 1) return;   // a second big component elsewhere
  // ---------------------------------------------------------------------------
  BS Dy; int hy; if (ynew) { Dy.clear(); Dy.set(0); hy = 0; } else { Dy = D0[y]; hy = hiD[y]; }
  BS U; U.clear(); BS RnotF; for (int i = 0; i < NW; i++) RnotF.w[i] = R.w[i] | ~FULL.w[i];   // values a new distance may not take
  // new distances = union of translates; each translate must avoid R (realised), FULL^c (not a target value) and the
  // translates already accumulated (a distance obtained twice) -> early exit per translate
  if (ncx <= ncy) { for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); int sh = dist_[xi][x] + t; if (sh + hy > N) return; BS T = Dy.shl(sh); if (T.inter(RnotF) || T.inter(U)) return; U.orw(T); } }
  else { const BS& Dx = D0[x]; int hx = hiD[x]; for (u32 m = my; m; m &= m - 1) { int yj = __builtin_ctz(m); int sh = (ynew ? 0 : dist_[yj][y]) + t; if (sh + hx > N) return; BS T = Dx.shl(sh); if (T.inter(RnotF) || T.inter(U)) return; U.orw(T); } }
  int lv = ne; saveV[lv] = V; int cxid = comp[x], cyid = ynew ? y : comp[y];
  saveCm[lv][0] = cm[cxid]; if (!ynew) saveCm[lv][1] = cm[cyid];
  for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); saveD[lv][xi] = D0[xi]; saveHi[lv][xi] = hiD[xi]; saveHiH[lv][xi] = hiH[xi]; }
  for (u32 m = my; m; m &= m - 1) { int yj = __builtin_ctz(m); saveD[lv][yj] = D0[yj]; saveHi[lv][yj] = hiD[yj]; saveHiH[lv][yj] = hiH[yj]; }
  saveBig[lv] = bigCnt;   // D4
  if (ynew) { V++; comp[y] = y; cm[y] = 1u << y; D0[y].clear(); D0[y].set(0); hiD[y] = 0; hiH[y] = 0; saveHiH[lv][y] = 0; }
  for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); for (u32 m2 = my; m2; m2 &= m2 - 1) { int yj = __builtin_ctz(m2); int d = dist_[xi][x] + t + (ynew ? 0 : dist_[yj][y]); dist_[xi][yj] = dist_[yj][xi] = d;
    int h = hop_[xi][x] + 1 + (ynew ? 0 : hop_[yj][y]); hop_[xi][yj] = hop_[yj][xi] = h; } }
  { BS Dx = D0[x]; int hx = hiD[x]; int hxH = hiH[x], hyH = eccyH;
    for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); int sh = dist_[xi][x] + t; D0[xi].orw(Dy.shl(sh)); hiD[xi] = max(hiD[xi], sh + hy); hiH[xi] = max(hiH[xi], hop_[xi][x] + 1 + hyH); }
    for (u32 m = my; m; m &= m - 1) { int yj = __builtin_ctz(m); int sh = (ynew ? 0 : dist_[yj][y]) + t; D0[yj].orw(Dx.shl(sh)); hiD[yj] = max(hiD[yj], sh + hx); hiH[yj] = max(hiH[yj], (ynew ? 0 : hop_[yj][y]) + 1 + hxH); } }
  bigCnt += (ndiam >= 3 ? 1 : 0) - wasBig;   // D4
  for (u32 m = my; m; m &= m - 1) comp[__builtin_ctz(m)] = cxid;
  cm[cxid] = mx | my;
  R.orw(U); eu[ne] = x; ev[ne] = y; ew[ne] = t; ne++;
  rec();
  ne--; for (int i = 0; i < NW; i++) R.w[i] &= ~U.w[i];
  bigCnt = saveBig[lv];   // D4
  for (u32 m = mx; m; m &= m - 1) { int xi = __builtin_ctz(m); D0[xi] = saveD[lv][xi]; hiD[xi] = saveHi[lv][xi]; hiH[xi] = saveHiH[lv][xi]; }
  for (u32 m = my; m; m &= m - 1) { int yj = __builtin_ctz(m); D0[yj] = saveD[lv][yj]; hiD[yj] = saveHi[lv][yj]; hiH[yj] = saveHiH[lv][yj]; comp[yj] = cyid; }
  cm[cxid] = saveCm[lv][0]; if (!ynew) cm[cyid] = saveCm[lv][1];
  V = saveV[lv];
}
static void rec() {
  if (aborted) return;
  nodes++; depthHist[ne]++; { int nc = V - ne; if (nc > 7) nc = 7; ncompHist[ne][nc]++; }
  if (nodeLimit > 0 && nodes >= nodeLimit) { aborted = true; return; }
  if (ne == shardLevel && shardK > 1) { if ((shardCnt++) % shardK != shardI) return; }
  BS RnotF; for (int i = 0; i < NW; i++) RnotF.w[i] = R.w[i] | ~FULL.w[i];
  int t = R.lowestMissingIn(FULL, 1, N);
  if (t > N) { if (ne == E && V == n) { nsol++; if (printSol) { printf("SOL:"); for (int i = 0; i < ne; i++) printf(" %d-%d:%d", eu[i], ev[i], ew[i]); printf("\n"); fflush(stdout); } } return; }
  if (ne >= E) return;
  if (ne > 0 && t + ew[ne - 1] > N) return;                     // any two edges lie on a common path: w_i + w_j <= N
  if (t > N - n + 2) return;                                    // D4(universal): every edge has c_e >= n-1 (Lemma 4c)
  int ncomp = V - ne; if (E - ne < ncomp - 1 + (n - V)) return;   // each remaining edge fixes at most one unit of deficit
#ifndef D4_NO_ENDGAME
  if (ncomp >= 2 && E - ne >= 2) {                                 // D4 endgame feasibility
    u32 seen = 0, mbig = 0;
    for (int i = 0; i < V; i++) { u32 c = cm[comp[i]]; if (seen & c) continue; seen |= c;
      bool isbig = false; for (u32 m = c; m; m &= m - 1) if (hiH[__builtin_ctz(m)] >= 3) { isbig = true; break; }
      if (isbig) { mbig = c; break; } }
    if (mbig) {                                                    // big comp exists: joint assembly test
      int cands[MAXV], ncand = 0;
      for (u32 m = mbig; m; m &= m - 1) { int i = __builtin_ctz(m); if (hiH[i] <= 2) cands[ncand++] = i; }
      if (ncand == 0) return;
      int stars[MAXV], nst = 0; u32 seen2 = 0;
      for (int i = 0; i < V; i++) { u32 c = cm[comp[i]]; if (c == mbig || (seen2 & c)) continue; seen2 |= c;
        int s = -1, be = 99; for (u32 m = c; m; m &= m - 1) { int j = __builtin_ctz(m); if (hiH[j] < be) { be = hiH[j]; s = j; } }
        stars[nst++] = s; }
      BS weakSets[MAXV];
      for (int i = 0; i < nst; i++) weakFeas(stars[i], t, RnotF, weakSets[i]);
      int minxi_forced = (E - ne == ncomp - 1) ? t : 0;
      bool okAny = false;
      for (int ci = 0; ci < ncand && !okAny; ci++) {
        int c0 = cands[ci];
        BS dom[MAXV]; bool dead = false;
        for (int i = 0; i < nst; i++) { feasForCand(mbig, c0, stars[i], weakSets[i], RnotF, dom[i]);
          bool empty = true; for (int w = 0; w < NW; w++) if (dom[i].w[w]) { empty = false; break; }
          if (empty) { dead = true; break; } }
        if (dead) continue;
        // order by domain size (fail-first)
        int ordr[MAXV]; for (int i = 0; i < nst; i++) ordr[i] = i;
        for (int a = 0; a < nst; a++) for (int b = a + 1; b < nst; b++)
          if (dom[ordr[b]].count() < dom[ordr[a]].count()) { int tmp = ordr[a]; ordr[a] = ordr[b]; ordr[b] = tmp; }
        BS domOrd[MAXV]; for (int i = 0; i < nst; i++) domOrd[i] = dom[ordr[i]];
        // if the forced-min-xi applies, it applies to WHICHEVER star joins first; our CSP fixes an order, so
        // only enforce it when nst == 1 (single join) -- otherwise skip the constraint (sound relaxation).
        int mf = (nst == 1) ? minxi_forced : 0;
        BS vals; vals.clear();
        cspBudget = 20000;
        if (cspGo(domOrd, 0, nst, RnotF, vals, mf)) okAny = true;
      }
      if (!okAny) return;
    } else {                                                       // all comps are stars: at most one holds c
      int nbad = 0; u32 seen2 = 0;
      for (int i = 0; i < V && nbad < 2; i++) { u32 c = cm[comp[i]]; if (seen2 & c) continue; seen2 |= c;
        int s = -1, be = 99; for (u32 m = c; m; m &= m - 1) { int j = __builtin_ctz(m); if (hiH[j] < be) { be = hiH[j]; s = j; } }
        BS feas; weakFeas(s, t, RnotF, feas);
        bool empty = true; for (int w = 0; w < NW; w++) if (feas.w[w]) { empty = false; break; }
        if (empty) nbad++;
      }
      if (nbad >= 2) return;
    }
  }
#endif
  u32 elig = 0; for (int i = 0; i < V; i++) { u32 c = cm[comp[i]]; if (__builtin_popcount(c) == 2 && (int)__builtin_ctz(c) != i) continue;
    if (hiD[i] + t > N) continue; BS T = D0[i].shl(t); if (T.inter(RnotF)) continue;   // x itself must be a valid attachment point at weight t
    elig |= 1u << i; }
  for (u32 m = elig; m; m &= m - 1) { int x = __builtin_ctz(m); u32 rest = elig & ~cm[comp[x]] & ~((2u << x) - 1); for (u32 m2 = rest; m2; m2 &= m2 - 1) tryAdd(x, __builtin_ctz(m2), t, false); }
  if (V < n) for (u32 m = elig; m; m &= m - 1) tryAdd(__builtin_ctz(m), V, t, true);
  if (V + 2 <= n && FULL.test(t)) { int x = V, y = V + 1; int lv = ne; saveV[lv] = V; V += 2; comp[x] = x; comp[y] = x; cm[x] = (1u << x) | (1u << y); dist_[x][y] = dist_[y][x] = t;
    hop_[x][y] = hop_[y][x] = 1; hiH[x] = hiH[y] = 1;   // D4
    D0[x].clear(); D0[x].set(0); D0[x].set(t); D0[y] = D0[x]; hiD[x] = hiD[y] = t; R.set(t); eu[ne] = x; ev[ne] = y; ew[ne] = t; ne++; rec(); ne--; R.reset(t); V = saveV[lv]; }
}
int main(int argc, char** argv) {
  if (argc < 2) { fprintf(stderr, "usage: forest_search n [--target v1,v2,...] [--shard i K] [--shard-level L] [--nodes L] [-q]\n"); return 1; }
  n = atoi(argv[1]); N = n * (n - 1) / 2; E = n - 1; V = 0; R.clear(); FULL.clear(); bool haveT = false;
  for (int i = 2; i < argc; i++) {
    if (!strcmp(argv[i], "--target")) { haveT = true; N = 0; const char* q = argv[++i]; while (*q) { int v = atoi(q); FULL.set(v); if (v > N) N = v; while (*q && *q != ',') q++; if (*q) q++; } }
    else if (!strcmp(argv[i], "--shard")) { shardI = atoi(argv[++i]); shardK = atoi(argv[++i]); }
    else if (!strcmp(argv[i], "--shard-level")) shardLevel = atoi(argv[++i]);
    else if (!strcmp(argv[i], "--nodes")) nodeLimit = atoll(argv[++i]);
    else if (!strcmp(argv[i], "-q")) printSol = false;
  }
  if (!haveT) for (int v = 1; v <= N; v++) FULL.set(v);
  if (n > MAXV - 1 || N > 64 * NW - 2) { fprintf(stderr, "n too large for this build\n"); return 1; }
  auto t0 = chrono::steady_clock::now();
  rec();
  double dt = chrono::duration<double>(chrono::steady_clock::now() - t0).count();
  printf("{\"n\": %d, \"status\": \"%s\", \"nsol\": %lld, \"nodes\": %lld, \"time\": %.3f, \"shard\": [%d, %d, %d]}\n", n, aborted ? "UNKNOWN" : "DONE", nsol, nodes, dt, shardI, shardK, shardLevel);
  fprintf(stderr, "n=%d nodes=%lld nsol=%lld time=%.2f\ndepth:", n, nodes, nsol, dt); for (int d = 0; d <= E; d++) fprintf(stderr, " %d:%lld", d, depthHist[d]); fprintf(stderr, "\n");
  for (int d = 0; d <= E; d++) { fprintf(stderr, "depth %2d by ncomp:", d); for (int c = 0; c < 8; c++) if (ncompHist[d][c]) fprintf(stderr, " %d:%lld", c, ncompHist[d][c]); fprintf(stderr, "\n"); }
  return 0;
}
